// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'accionesCard': string;

  'activo': string;

  'badgeEstado': string;

  'bntCancelar': string;

  'btnClose': string;

  'btnFinalizar': string;

  'btnLaunch': string;

  'btnNuevaObra': string;

  'btnUpload': string;

  'cancelado': string;

  'container': string;

  'detailColumn': string;

  'detailContent': string;

  'detailTitle': string;

  'dwgIcon': string;

  'emptyIcon': string;

  'emptyState': string;

  'filledAhead': string;

  'filledDelayed': string;

  'filledOnTrack': string;

  'finalizado': string;

  'fotoCard': string;

  'fotoComentarioBox': string;

  'fotoComentarioText': string;

  'fotoFecha': string;

  'fotoThumb': string;

  'headerSection': string;

  'historialSection': string;

  'iconVerde': string;

  'infoSection': string;

  'labelSeccion': string;

  'listColumn': string;

  'listContainer': string;

  'listGroupHeader': string;

  'listItem': string;

  'modalBody': string;

  'modalContent': string;

  'modalFlotanteContainer': string;

  'modalFooter': string;

  'modalHeader': string;

  'modalSeparator': string;

  'modalTitle': string;

  'obraTitle': string;

  'pdfIcon': string;

  'planoCard': string;

  'planosSection': string;

  'progressTrackerBox': string;

  'sectionTitle': string;

  'selected': string;

  'splitLayout': string;

  'subtituloHeader': string;

  'tituloPrincipal': string;

  'trackerDot': string;

}

declare const strings: IExportStyles;

export default strings;