// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'cardContent': string;

  'cardGrid': string;

  'cardHeader': string;

  'comentarioBox': string;

  'comentarios': string;

  'container': string;

  'fechaText': string;

  'footerOperario': string;

  'headerSection': string;

  'iconOperario': string;

  'imageContainer': string;

  'loader': string;

  'obraName': string;

  'reporteCard': string;

  'reporteImagen': string;

  'searchBar': string;

  'subtitulo': string;

  'titulo': string;

}

declare const strings: IExportStyles;

export default strings;