// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'active': string;

  'appHeader': string;

  'bigIcon': string;

  'btnAmarillo': string;

  'btnEws': string;

  'btnNaranja': string;

  'btnRojo': string;

  'btnVerde': string;

  'container': string;

  'dot': string;

  'extraSection': string;

  'fadeInRight': string;

  'gpsBadge': string;

  'instruccion': string;

  'mainContent': string;

  'obraCard': string;

  'obraTitle': string;

  'photoDropzone': string;

  'previewContainer': string;

  'previewItem': string;

  'progressBtn': string;

  'progressContainer': string;

  'removePhoto': string;

  'selected': string;

  'stepContainer': string;

  'stepTitle': string;

  'subtitle': string;

  'teamList': string;

  'teamMemberItem': string;

  'title': string;

  'userCard': string;

  'wizardNav': string;

}

declare const strings: IExportStyles;

export default strings;