// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'asignadosConsola': string;

  'cellObra': string;

  'colDia': string;

  'colObra': string;

  'draggablePersonaCard': string;

  'dropZone': string;

  'emptyText': string;

  'fotoAsignada': string;

  'panelTituloCompacto': string;

  'pendingItem': string;

  'pendingList': string;

  'pendingName': string;

  'pendingPanel': string;

  'pendingReason': string;

  'personalListHorizontal': string;

  'personalPanelTop': string;

  'planTable': string;

  'tableContainer': string;

  'titulo': string;

  'vistaPlanificacion': string;

}

declare const strings: IExportStyles;

export default strings;