// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'avatarArea': string;

  'btnConfirmDelete': string;

  'btnDelete': string;

  'btnNuevo': string;

  'btnPanelPrimary': string;

  'cardEmpleado': string;

  'cardEmpleadoShimmer': string;

  'cardSeparator': string;

  'cargo': string;

  'container': string;

  'editButton': string;

  'editOverlay': string;

  'fadeInDown': string;

  'fullWidth': string;

  'gridPersonal': string;

  'headerSection': string;

  'iconCargo': string;

  'iconContact': string;

  'idEmpleado': string;

  'modalBody': string;

  'modalContent': string;

  'modalFlotante': string;

  'modalFooter': string;

  'modalHeader': string;

  'modalSeparator': string;

  'modalTitle': string;

  'nombre': string;

  'previewBox': string;

  'previewTitle': string;

  'shimmerSeparator': string;

  'subtitulo': string;

  'tituloPrincipal': string;

}

declare const strings: IExportStyles;

export default strings;