// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'actionBtn': string;

  'btnAdd': string;

  'container': string;

  'deleteBtn': string;

  'formCard': string;

  'formTitle': string;

  'gridForm': string;

  'panelStack': string;

  'searchSection': string;

  'stockCellAlerta': string;

  'stockCellNormal': string;

  'tableContainer': string;

}

declare const strings: IExportStyles;

export default strings;