// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'container': string;

  'deleteBtn': string;

  'emptyText': string;

  'gridObras': string;

  'obraCard': string;

  'obraHeader': string;

  'obraTitle': string;

  'obraUbicacion': string;

  'panelAsignacion': string;

  'panelTitle': string;

  'personaName': string;

  'personalList': string;

  'personalRow': string;

  'semaforoText': string;

  'separator': string;

  'subtitle': string;

  'title': string;

}

declare const strings: IExportStyles;

export default strings;