// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'appWrapper': string;

  'header': string;

  'headerLeft': string;

  'headerRight': string;

  'isOpen': string;

  'logoArea': string;

  'mainContent': string;

  'menuButton': string;

  'obras': string;

  'overlay': string;

  'pageBody': string;

  'sidebar': string;

}

declare const strings: IExportStyles;

export default strings;